library:
  source-dirs: src
tests:
  over-zealous-test:
    source-dirs: test
    main: TestReg.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - over-zealous
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- containers
- containers
- base >= 4.7 && < 5
- QuickCheck
name: over-zealous
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/over-zealous
license: BSD3
executables:
  over-zealous-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - over-zealous
description: Please see the README on GitHub at <https://github.com/githubuser/over-zealous#readme>
